name: Build Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build the Spring Boot application
        run: ./mvnw clean package



      # Add additional steps here as needed, such as deploying or packaging artifacts.
